[project]
name = "xiaoshuo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.16",
    "flask[async]>=3.1.0",
    "google-generativeai>=0.8.5",
    "openai>=1.75.0",
    "requests>=2.32.3",
]
